task:
  name: Build
  timeout_in: 3h
  container:
    image: apon77/aosp:ccache
  env:
    USE_CCACHE: 1
    ROM_NAME: "sed -n '4p' < $CIRRUS_WORKING_DIR/build_rom.sh | cut -d / -f 4"
  build_script:
    - set -exv
    - mkdir -p ~/roms/$(bash -c "$ROM_NAME")
    - cd ~/roms/$(bash -c "$ROM_NAME")
    - rm -rf .repo/local_manifests
    - export CCACHE_DIR=/home/ci/ccache/$(bash -c "$ROM_NAME")/$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh | cut -d _ -f 2 | cut -d - -f 1)
    - ccache -z
    - bash $CIRRUS_WORKING_DIR/build_rom.sh
    - ccache -s
    - rm -rf out/target/product/$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh | cut -d _ -f 2 | cut -d - -f 1)
