task:
  name: Build
  persistent_worker:
    isolation:
      container:
        image: apon77/aosp:ccache
        cpu: 24
        memory: 60g
        volumes:
          - /home/cirrus/roms:/home/ci/roms
          - /home/cirrus/ccache:/home/ci/ccache
          - /home/cirrus/.config:/home/ci/.config
  env:
    USE_CCACHE: 1
    ROM_NAME: "grep init $CIRRUS_WORKING_DIR/build_rom.sh| cut -d / -f 4"
  sync_script:
    - set -exv
    - mkdir -p ~/roms/$(bash -c "$ROM_NAME")
    - cd ~/roms/$(bash -c "$ROM_NAME")
    - rm -rf .repo/local_manifests
    - command=$(head $CIRRUS_WORKING_DIR/build_rom.sh -n $(expr $(grep build/ $CIRRUS_WORKING_DIR/build_rom.sh -n | cut -f1 -d:) - 1))
    - bash -c "$command"
  build_script:
    - set -exv
    - cd ~/roms/$(bash -c "$ROM_NAME")
    - export CCACHE_DIR=/home/ci/ccache/$(bash -c "$ROM_NAME")/$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh | cut -d _ -f 2 | cut -d - -f 1)
    - ccache -z
    - command=$(tail $CIRRUS_WORKING_DIR/build_rom.sh -n $(expr $(grep build/ $CIRRUS_WORKING_DIR/build_rom.sh -n | cut -f1 -d:) - 1)| head -n -1)
    - bash -c "$command"
  ccache_stats_script:
    - set -exv
    - export CCACHE_DIR=/home/ci/ccache/$(bash -c "$ROM_NAME")/$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh | cut -d _ -f 2 | cut -d - -f 1)
    - ccache -s
  upload_script:
    - set -exv
    - cd ~/roms/$(bash -c "$ROM_NAME")
    - command=$(tail $CIRRUS_WORKING_DIR/build_rom.sh -n 1)
    - bash -c "$command"
  remove_script:
    - set -exv
    - cd ~/roms/$(bash -c "$ROM_NAME")
    - rm -rf out/target/product/$(grep unch $CIRRUS_WORKING_DIR/build_rom.sh | cut -d _ -f 2 | cut -d - -f 1)
